# Generated by Django 4.1.4 on 2023-03-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=255)),
                ('descriere', models.TextField(blank=True)),
                ('eticheta', models.CharField(db_index=True, max_length=255)),
                ('stres', models.DecimalField(decimal_places=0, max_digits=3)),
                ('nivelEnergie', models.DecimalField(decimal_places=0, max_digits=1)),
                ('durata', models.DecimalField(decimal_places=0, max_digits=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
