# Generated by Django 4.1.4 on 2023-03-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamcatcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vis',
            new_name='Dream',
        ),
    ]
