# Generated by Django 4.1.4 on 2023-03-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamcatcher', '0002_rename_vis_dream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
